// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3wrRrAyFukTm-z5bGmxOlP2B0vBDX4HA',
    appId: '1:654954368340:web:9e6b1aece87f03b8ba0cc1',
    messagingSenderId: '654954368340',
    projectId: 'vibzcheck-96c4d',
    authDomain: 'vibzcheck-96c4d.firebaseapp.com',
    storageBucket: 'vibzcheck-96c4d.firebasestorage.app',
    measurementId: 'G-K6JXHJNB2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_wIpuqumY_vNvkMdvBRdNT7Tp8ZY9G8',
    appId: '1:654954368340:android:4007f86723c4a7d6ba0cc1',
    messagingSenderId: '654954368340',
    projectId: 'vibzcheck-96c4d',
    storageBucket: 'vibzcheck-96c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBDTT1i_aYAfa_PI1gfAfEaUfFdQqcLQ',
    appId: '1:654954368340:ios:1851f0cd19e35fd3ba0cc1',
    messagingSenderId: '654954368340',
    projectId: 'vibzcheck-96c4d',
    storageBucket: 'vibzcheck-96c4d.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOBDTT1i_aYAfa_PI1gfAfEaUfFdQqcLQ',
    appId: '1:654954368340:ios:1851f0cd19e35fd3ba0cc1',
    messagingSenderId: '654954368340',
    projectId: 'vibzcheck-96c4d',
    storageBucket: 'vibzcheck-96c4d.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3wrRrAyFukTm-z5bGmxOlP2B0vBDX4HA',
    appId: '1:654954368340:web:e464bb9a3dc00344ba0cc1',
    messagingSenderId: '654954368340',
    projectId: 'vibzcheck-96c4d',
    authDomain: 'vibzcheck-96c4d.firebaseapp.com',
    storageBucket: 'vibzcheck-96c4d.firebasestorage.app',
    measurementId: 'G-13Z2QR7S0J',
  );
}
